services:
  - type: web
    name: generateur-facture
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn generateur_facture.wsgi:application"
    envVars:
      - key: RENDER
        value: "true"
